### ISSUE TITLE
hardcoding apikey in values.yaml

### ISSUE THREAD

**Issue by gespi1** [checkly/checkly-k8s#3]
Hi 👋 

Seems like the way to inject your apikey is via the values.yaml which is not best practice. I would like to open a PR to fix this.

**Proposal:**

Allow user to bring in their pre-existing secret or use a field called `extraManifests` to define a resource that will create that secret (e.g. [external secrets](https://github.com/external-secrets/external-secrets)) for the chart to consume. 

**Implementation:**

The following will create the secret the way this chart already does it but in the new structure.
```
apiKeySecret:
  create: <bool> default: true
  apiKey: <string>
```

The following will not have the chart create the secret but will consume an already existing secret in a cluster
```
apiKeySecret:
  create: false
  name: <string> # name of the secret that will be consumed
```

The following will have the chart create the secret but this time via extraManifests and then will be consumed
```
apiKeySecret:
  create: false
  name: checkly-agent-secret

extraManifests: #allows users to define any extra kubernetes resources they think they might need to make this chart work with their infra 
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
       name: checkly-agent-secret
       namespace: monitoring
    spec:
       target:
         name: my-checkly-secrets-in-aws
```

we can add helpers to determine if `create: true`  then `apiKey` will be mandatory. Same with `create: false` and `name`. We can even say that `apiKey` and `name` cannot both exist
